### ISSUE TITLE
Problems with deplyment on EC2

### ISSUE THREAD

**Issue by sanvir10** [input-output-hk/rscoin-haskell#3]
I follow the steps for EC2 deplyment but when i execute admin/autoinstall  i get

cp: missing destination file operand after '/nix/store/87xpq8r525g7xg5113inbrz605xbfa0s-rscoin-block-explorer/share'
Try 'cp --help' for more information.
builder for ‘/nix/store/kywmqq9l9kp2cm00kv0c2yn7df90jxwy-rscoin-block-explorer.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/rzbn6vjzcfpwvfyyp3fi9ijxmksjhmlq-nginx.conf.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/b871bxv7g7gm1cccjqhmz9vkr9hh3cdh-rscoin-core-5b2a65d’
cannot build derivation ‘/nix/store/xyqd30mhrc419946disk0jrj0v4cixzz-unit-nginx.service.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/3dgrmrw8q6bcjvc5kywh39w2mj5y05ww-system-units.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/zyxyj3hv720sf86kfdcrxyi46f200q50-etc.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/jhz8m1n3pn4bgk9ycn4514ypgm6l0lq3-nixos-system-block-explorer-16.09.git.6b20d5b.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/x0fr0dp4mp52fqzanc9kxmzji08q8ld9-nixops-machines.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/x0fr0dp4mp52fqzanc9kxmzji08q8ld9-nixops-machines.drv’ failed
error: unable to build all machine configurations
Querying bank key
cat: /var/lib/rscoin-bank/.rscoin/bankKey.pub: No such file or directory
[Error]. Bank key wasn't retrieved. Exiting.

I would like know why this error message.

**Comment by volhovm** [comment]
To be more precise, i should know what version of deployment configs are you using first of all (repository, commit). Autoinstall is from this outdated repo i suppose: https://github.com/input-output-hk/rscoin-nixops. It was significantly changed over past month and new version is not yet public.

**Comment by sanvir10** [comment]
Thanks for response, i have the repo updated

b15e64ce64901e49fe93137835fe94cb6ff222d0 refs/heads/master
b15e64ce64901e49fe93137835fe94cb6ff222d0 refs/remotes/origin/HEAD
b15e64ce64901e49fe93137835fe94cb6ff222d0 refs/remotes/origin/master

i'm using this ami for deployment: nixos-16.03.659.011ea84-x86_64-hvm-ebs - ami-265dad46, the instances are created but with the error message.

![2016-10-25 14-22-01](https://cloud.githubusercontent.com/assets/12051806/19700837/7d38b8a0-9abe-11e6-9e02-da09948a0c10.png)

if you have recent info can you shared me, how use the proyect, Thanks in advance

**Comment by volhovm** [comment]
@sanvir10 most probably you're using the different repository b/c i didn't manage to find this commit in the history. Once again, correct version is closed-source for now. Contact me or someone competent from IOHK to get access to it.

Most probably I will manage to open-source the part of new `rscoin` deployment relatively soon, but anyway not this week. I can share raw untested configs on the weekends actually, so if you're fluent with nix you'll manage to fix them in an hour or so. Ping me here next week anyway.

**Comment by sanvir10** [comment]
Sorry the commit is from this repo https://github.com/input-output-hk/rscoin-nixops.git.

Ok, then next week i'll wait for the open source, regards.
